// Types of data grid where pre-sets are in effect.
export const presetTypes = [
	"circulationStatus",
	"patronRequestsLibraryException",
	"patronRequestsLibraryActive",
	"patronRequestsLibraryOutOfSequence",
	"patronRequestsLibraryCompleted",
	"patronRequestsLibraryAll",
	"patronRequestsException",
	"patronRequestsActive",
	"patronRequestsAll",
	"patronRequestsOutOfSequence",
	"patronRequestsCompleted",
	"referenceValueMappings",
	"numericRangeMappings",
	"referenceValueMappingsForLibraryPatronSecondHostLms",
	"referenceValueMappingsForLibraryPatron",
	"referenceValueMappingsForLibraryLocation",
	"referenceValueMappingsForLibraryLocationSecondHostLMS",
	"referenceValueMappingsForLibraryItemType",
	"referenceValueMappingsForLibraryItemTypeSecondHostLms",
	"numericRangeMappingsForLibraryPatron",
	"numericRangeMappingsForLibraryPatronSecondHostLms",
	"numericRangeMappingsForLibraryItemTypeSecondHostLms",
	"numericRangeMappingsForLibraryItemType",
	"numericRangeMappingsForLibraryAll",
	"numericRangeMappingsForLibraryAllSecondHostLms",
	"referenceValueMappingsForLibraryAll",
	"referenceValueMappingsForLibraryAllSecondHostLms",
	"libraryLocations",
	"supplierRequestsLibrary",
];

// Types of data grid where users cannot click through to a details page
export const nonClickableTypes = [
	"referenceValueMappings",
	"ReferenceValueMappings",
	"numericRangeMappings",
	"circulationStatus",
	"referenceValueMappingsForLibraryPatronSecondHostLms",
	"referenceValueMappingsForLibraryPatron",
	"referenceValueMappingsForLibraryLocation",
	"referenceValueMappingsForLibraryLocationSecondHostLMS",
	"referenceValueMappingsForLibraryItemType",
	"referenceValueMappingsForLibraryItemTypeSecondHostLms",
	"numericRangeMappingsForLibraryPatron",
	"numericRangeMappingsForLibraryPatronSecondHostLms",
	"numericRangeMappingsForLibraryItemTypeSecondHostLms",
	"numericRangeMappingsForLibraryItemType",
	"numericRangeMappingsForLibraryItemTypeSecondHostLms",
	"numericRangeMappingsForLibraryAll",
	"numericRangeMappingsForLibraryAllSecondHostLms",
	"referenceValueMappingsForLibraryAll",
	"referenceValueMappingsForLibraryAllSecondHostLms",
	"alarms",
];

// Types of data grid where users can click through to a details page,
// but where special redirection is needed to get the correct URL
export const specialRedirectionTypes = [
	"patronRequestsLibraryActive",
	"patronRequestsLibraryOutOfSequence",
	"patronRequestsLibraryCompleted",
	"patronRequestsLibraryException",
	"patronRequestsLibraryAll",
	"patronRequestsActive",
	"patronRequestsOutOfSequence",
	"patronRequestsCompleted",
	"patronRequestsException",
	"dataChangeLog",
	"welcomeLibraries",
	"libraryLocations",
	"supplierRequestsLibrary",
];

// Types of data grid where we show the actions menu to the user.
export const actionsTypes = [
	"libraries",
	"welcomeLibraries",
	"locations",
	"referenceValueMappings",
	"numericRangeMappings",
	"circulationStatus",
	"referenceValueMappingsForLibraryPatronSecondHostLms",
	"referenceValueMappingsForLibraryPatron",
	"referenceValueMappingsForLibraryLocation",
	"referenceValueMappingsForLibraryLocationSecondHostLMS",
	"referenceValueMappingsForLibraryItemType",
	"referenceValueMappingsForLibraryItemTypeSecondHostLms",
	"numericRangeMappingsForLibraryPatron",
	"numericRangeMappingsForLibraryPatronSecondHostLms",
	"numericRangeMappingsForLibraryItemTypeSecondHostLms",
	"numericRangeMappingsForLibraryItemType",
	"libraryLocations",
];
