import { AuditItem } from "./AuditItem";
import { ClusterRecord } from "./ClusterRecord";
import { Patron } from "./Patron";
import { PatronIdentity } from "./PatronIdentity";
import { SupplierRequest } from "./SupplierRequest";

export interface PatronRequest {
	id: string;
	dateCreated?: string | null;
	dateUpdated?: string | null;
	patronHostlmsCode?: string | null;
	patron?: Patron | null;
	requestingIdentity?: PatronIdentity | null;
	bibClusterId?: string | null; // ID
	pickupLocationCode?: string | null;
	pickupPatronId?: string | null;
	pickupItemId?: string | null;
	pickupItemType?: string | null;
	pickupItemStatus?: string | null;
	pickupRequestId?: string | null;
	pickupRequestStatus?: string | null;
	status?: string | null;
	localRequestId?: string | null;
	localRequestStatus?: string | null;
	localItemId?: string | null;
	localItemStatus?: string | null;
	localItemType?: string | null;
	localBibId?: string | null;
	description?: string | null;
	nextScheduledPoll?: string | null;
	errorMessage?: string | null;
	activeWorkflow?: string | null;
	requesterNote?: string | null;
	suppliers?: (SupplierRequest | null)[] | null;
	audit?: (AuditItem | null)[] | null;
	clusterRecord?: ClusterRecord | null;
	previousStatus?: string | null;
	pollCountForCurrentStatus?: number | null;
	manualPollCountForCurrentStatus?: number | null;
	autoPollCountForCurrentStatus?: number | null;
	currentStatusTimestamp?: string | null;
	nextExpectedStatus?: string | null;
	outOfSequenceFlag?: boolean | null;
	elapsedTimeInCurrentStatus?: number | null;
	rawLocalItemStatus?: string | null;
	rawLocalRequestStatus?: string | null;
	localItemHostlmsCode?: string | null;
	localItemAgencyCode?: string | null;
	isManuallySelectedItem?: boolean | null;
	resolutionCount?: number | null;
	renewalCount?: number | null;
	localRenewalCount?: number | null;
	rawPickupItemStatus?: string | null;
	rawPickupRequestStatus?: string | null;
	pickupBibId?: string | null;
	pickupItemBarcode?: string | null;
	isExpeditedCheckout?: boolean | null;
	localHoldingId?: string | null;
	pickupHoldingId?: string | null;
}
