/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PatronRequestsImport } from './routes/patronRequests'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PatronRequestsRoute = PatronRequestsImport.update({
  id: '/patronRequests',
  path: '/patronRequests',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/patronRequests': {
      id: '/patronRequests'
      path: '/patronRequests'
      fullPath: '/patronRequests'
      preLoaderRoute: typeof PatronRequestsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patronRequests': typeof PatronRequestsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patronRequests': typeof PatronRequestsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/patronRequests': typeof PatronRequestsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patronRequests'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patronRequests'
  id: '__root__' | '/' | '/patronRequests'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatronRequestsRoute: typeof PatronRequestsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatronRequestsRoute: PatronRequestsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/patronRequests"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/patronRequests": {
      "filePath": "patronRequests.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
