/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as _authenticatedRouteImport } from './routes/__authenticated'
import { Route as _authenticatedIndexRouteImport } from './routes/__authenticated/index'
import { Route as _authenticatedSupplierRequestsRouteImport } from './routes/__authenticated/supplierRequests'
import { Route as _authenticatedSettingsRouteImport } from './routes/__authenticated/settings'
import { Route as _authenticatedServiceRouteImport } from './routes/__authenticated/service'
import { Route as _authenticatedMappingsRouteImport } from './routes/__authenticated/mappings'
import { Route as _authenticatedIllRouteImport } from './routes/__authenticated/ill'
import { Route as _authenticatedDataChangeLogRouteImport } from './routes/__authenticated/dataChangeLog'
import { Route as _authenticatedContactsRouteImport } from './routes/__authenticated/contacts'
import { Route as _authenticatedRequestingIndexRouteImport } from './routes/__authenticated/requesting/index'
import { Route as _authenticatedPatronRequestsIndexRouteImport } from './routes/__authenticated/patronRequests/index'
import { Route as _authenticatedLocationsIndexRouteImport } from './routes/__authenticated/locations/index'
import { Route as _authenticatedIllPatronRequestsRouteImport } from './routes/__authenticated/ill.patronRequests'
import { Route as _authenticatedIllLoginRouteImport } from './routes/__authenticated/ill.login'
import { Route as _authenticatedRequestingRecordIdIndexRouteImport } from './routes/__authenticated/requesting/$recordId/index'
import { Route as _authenticatedPatronRequestsIdIndexRouteImport } from './routes/__authenticated/patronRequests/$id/index'
import { Route as _authenticatedLocationsIdIndexRouteImport } from './routes/__authenticated/locations/$id/index'
import { Route as _authenticatedIndexesIndexCodeIndexRouteImport } from './routes/__authenticated/indexes/$indexCode/index'
import { Route as _authenticatedPatronRequestsAuditsAuditIdIndexRouteImport } from './routes/__authenticated/patronRequests/audits/$auditId/index'
import { Route as _authenticatedIndexesIndexCodeRecordIdIndexRouteImport } from './routes/__authenticated/indexes/$indexCode/$recordId/index'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedRoute = _authenticatedRouteImport.update({
  id: '/__authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedIndexRoute = _authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedSupplierRequestsRoute =
  _authenticatedSupplierRequestsRouteImport.update({
    id: '/supplierRequests',
    path: '/supplierRequests',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedSettingsRoute = _authenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedServiceRoute = _authenticatedServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedMappingsRoute = _authenticatedMappingsRouteImport.update({
  id: '/mappings',
  path: '/mappings',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedIllRoute = _authenticatedIllRouteImport.update({
  id: '/ill',
  path: '/ill',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedDataChangeLogRoute =
  _authenticatedDataChangeLogRouteImport.update({
    id: '/dataChangeLog',
    path: '/dataChangeLog',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedContactsRoute = _authenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedRequestingIndexRoute =
  _authenticatedRequestingIndexRouteImport.update({
    id: '/requesting/',
    path: '/requesting/',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPatronRequestsIndexRoute =
  _authenticatedPatronRequestsIndexRouteImport.update({
    id: '/patronRequests/',
    path: '/patronRequests/',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedLocationsIndexRoute =
  _authenticatedLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedIllPatronRequestsRoute =
  _authenticatedIllPatronRequestsRouteImport.update({
    id: '/patronRequests',
    path: '/patronRequests',
    getParentRoute: () => _authenticatedIllRoute,
  } as any)
const _authenticatedIllLoginRoute = _authenticatedIllLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => _authenticatedIllRoute,
} as any)
const _authenticatedRequestingRecordIdIndexRoute =
  _authenticatedRequestingRecordIdIndexRouteImport.update({
    id: '/requesting/$recordId/',
    path: '/requesting/$recordId/',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPatronRequestsIdIndexRoute =
  _authenticatedPatronRequestsIdIndexRouteImport.update({
    id: '/patronRequests/$id/',
    path: '/patronRequests/$id/',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedLocationsIdIndexRoute =
  _authenticatedLocationsIdIndexRouteImport.update({
    id: '/locations/$id/',
    path: '/locations/$id/',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedIndexesIndexCodeIndexRoute =
  _authenticatedIndexesIndexCodeIndexRouteImport.update({
    id: '/indexes/$indexCode/',
    path: '/indexes/$indexCode/',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPatronRequestsAuditsAuditIdIndexRoute =
  _authenticatedPatronRequestsAuditsAuditIdIndexRouteImport.update({
    id: '/patronRequests/audits/$auditId/',
    path: '/patronRequests/audits/$auditId/',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedIndexesIndexCodeRecordIdIndexRoute =
  _authenticatedIndexesIndexCodeRecordIdIndexRouteImport.update({
    id: '/indexes/$indexCode/$recordId/',
    path: '/indexes/$indexCode/$recordId/',
    getParentRoute: () => _authenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/contacts': typeof _authenticatedContactsRoute
  '/dataChangeLog': typeof _authenticatedDataChangeLogRoute
  '/ill': typeof _authenticatedIllRouteWithChildren
  '/mappings': typeof _authenticatedMappingsRoute
  '/service': typeof _authenticatedServiceRoute
  '/settings': typeof _authenticatedSettingsRoute
  '/supplierRequests': typeof _authenticatedSupplierRequestsRoute
  '/': typeof _authenticatedIndexRoute
  '/ill/login': typeof _authenticatedIllLoginRoute
  '/ill/patronRequests': typeof _authenticatedIllPatronRequestsRoute
  '/locations': typeof _authenticatedLocationsIndexRoute
  '/patronRequests': typeof _authenticatedPatronRequestsIndexRoute
  '/requesting': typeof _authenticatedRequestingIndexRoute
  '/indexes/$indexCode': typeof _authenticatedIndexesIndexCodeIndexRoute
  '/locations/$id': typeof _authenticatedLocationsIdIndexRoute
  '/patronRequests/$id': typeof _authenticatedPatronRequestsIdIndexRoute
  '/requesting/$recordId': typeof _authenticatedRequestingRecordIdIndexRoute
  '/indexes/$indexCode/$recordId': typeof _authenticatedIndexesIndexCodeRecordIdIndexRoute
  '/patronRequests/audits/$auditId': typeof _authenticatedPatronRequestsAuditsAuditIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/contacts': typeof _authenticatedContactsRoute
  '/dataChangeLog': typeof _authenticatedDataChangeLogRoute
  '/ill': typeof _authenticatedIllRouteWithChildren
  '/mappings': typeof _authenticatedMappingsRoute
  '/service': typeof _authenticatedServiceRoute
  '/settings': typeof _authenticatedSettingsRoute
  '/supplierRequests': typeof _authenticatedSupplierRequestsRoute
  '/': typeof _authenticatedIndexRoute
  '/ill/login': typeof _authenticatedIllLoginRoute
  '/ill/patronRequests': typeof _authenticatedIllPatronRequestsRoute
  '/locations': typeof _authenticatedLocationsIndexRoute
  '/patronRequests': typeof _authenticatedPatronRequestsIndexRoute
  '/requesting': typeof _authenticatedRequestingIndexRoute
  '/indexes/$indexCode': typeof _authenticatedIndexesIndexCodeIndexRoute
  '/locations/$id': typeof _authenticatedLocationsIdIndexRoute
  '/patronRequests/$id': typeof _authenticatedPatronRequestsIdIndexRoute
  '/requesting/$recordId': typeof _authenticatedRequestingRecordIdIndexRoute
  '/indexes/$indexCode/$recordId': typeof _authenticatedIndexesIndexCodeRecordIdIndexRoute
  '/patronRequests/audits/$auditId': typeof _authenticatedPatronRequestsAuditsAuditIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__authenticated': typeof _authenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/__authenticated/contacts': typeof _authenticatedContactsRoute
  '/__authenticated/dataChangeLog': typeof _authenticatedDataChangeLogRoute
  '/__authenticated/ill': typeof _authenticatedIllRouteWithChildren
  '/__authenticated/mappings': typeof _authenticatedMappingsRoute
  '/__authenticated/service': typeof _authenticatedServiceRoute
  '/__authenticated/settings': typeof _authenticatedSettingsRoute
  '/__authenticated/supplierRequests': typeof _authenticatedSupplierRequestsRoute
  '/__authenticated/': typeof _authenticatedIndexRoute
  '/__authenticated/ill/login': typeof _authenticatedIllLoginRoute
  '/__authenticated/ill/patronRequests': typeof _authenticatedIllPatronRequestsRoute
  '/__authenticated/locations/': typeof _authenticatedLocationsIndexRoute
  '/__authenticated/patronRequests/': typeof _authenticatedPatronRequestsIndexRoute
  '/__authenticated/requesting/': typeof _authenticatedRequestingIndexRoute
  '/__authenticated/indexes/$indexCode/': typeof _authenticatedIndexesIndexCodeIndexRoute
  '/__authenticated/locations/$id/': typeof _authenticatedLocationsIdIndexRoute
  '/__authenticated/patronRequests/$id/': typeof _authenticatedPatronRequestsIdIndexRoute
  '/__authenticated/requesting/$recordId/': typeof _authenticatedRequestingRecordIdIndexRoute
  '/__authenticated/indexes/$indexCode/$recordId/': typeof _authenticatedIndexesIndexCodeRecordIdIndexRoute
  '/__authenticated/patronRequests/audits/$auditId/': typeof _authenticatedPatronRequestsAuditsAuditIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/logout'
    | '/contacts'
    | '/dataChangeLog'
    | '/ill'
    | '/mappings'
    | '/service'
    | '/settings'
    | '/supplierRequests'
    | '/'
    | '/ill/login'
    | '/ill/patronRequests'
    | '/locations'
    | '/patronRequests'
    | '/requesting'
    | '/indexes/$indexCode'
    | '/locations/$id'
    | '/patronRequests/$id'
    | '/requesting/$recordId'
    | '/indexes/$indexCode/$recordId'
    | '/patronRequests/audits/$auditId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/logout'
    | '/contacts'
    | '/dataChangeLog'
    | '/ill'
    | '/mappings'
    | '/service'
    | '/settings'
    | '/supplierRequests'
    | '/'
    | '/ill/login'
    | '/ill/patronRequests'
    | '/locations'
    | '/patronRequests'
    | '/requesting'
    | '/indexes/$indexCode'
    | '/locations/$id'
    | '/patronRequests/$id'
    | '/requesting/$recordId'
    | '/indexes/$indexCode/$recordId'
    | '/patronRequests/audits/$auditId'
  id:
    | '__root__'
    | '/__authenticated'
    | '/login'
    | '/logout'
    | '/__authenticated/contacts'
    | '/__authenticated/dataChangeLog'
    | '/__authenticated/ill'
    | '/__authenticated/mappings'
    | '/__authenticated/service'
    | '/__authenticated/settings'
    | '/__authenticated/supplierRequests'
    | '/__authenticated/'
    | '/__authenticated/ill/login'
    | '/__authenticated/ill/patronRequests'
    | '/__authenticated/locations/'
    | '/__authenticated/patronRequests/'
    | '/__authenticated/requesting/'
    | '/__authenticated/indexes/$indexCode/'
    | '/__authenticated/locations/$id/'
    | '/__authenticated/patronRequests/$id/'
    | '/__authenticated/requesting/$recordId/'
    | '/__authenticated/indexes/$indexCode/$recordId/'
    | '/__authenticated/patronRequests/audits/$auditId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authenticatedRoute: typeof _authenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated': {
      id: '/__authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated/': {
      id: '/__authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _authenticatedIndexRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/supplierRequests': {
      id: '/__authenticated/supplierRequests'
      path: '/supplierRequests'
      fullPath: '/supplierRequests'
      preLoaderRoute: typeof _authenticatedSupplierRequestsRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/settings': {
      id: '/__authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof _authenticatedSettingsRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/service': {
      id: '/__authenticated/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof _authenticatedServiceRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/mappings': {
      id: '/__authenticated/mappings'
      path: '/mappings'
      fullPath: '/mappings'
      preLoaderRoute: typeof _authenticatedMappingsRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/ill': {
      id: '/__authenticated/ill'
      path: '/ill'
      fullPath: '/ill'
      preLoaderRoute: typeof _authenticatedIllRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/dataChangeLog': {
      id: '/__authenticated/dataChangeLog'
      path: '/dataChangeLog'
      fullPath: '/dataChangeLog'
      preLoaderRoute: typeof _authenticatedDataChangeLogRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/contacts': {
      id: '/__authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof _authenticatedContactsRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/requesting/': {
      id: '/__authenticated/requesting/'
      path: '/requesting'
      fullPath: '/requesting'
      preLoaderRoute: typeof _authenticatedRequestingIndexRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/patronRequests/': {
      id: '/__authenticated/patronRequests/'
      path: '/patronRequests'
      fullPath: '/patronRequests'
      preLoaderRoute: typeof _authenticatedPatronRequestsIndexRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/locations/': {
      id: '/__authenticated/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof _authenticatedLocationsIndexRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/ill/patronRequests': {
      id: '/__authenticated/ill/patronRequests'
      path: '/patronRequests'
      fullPath: '/ill/patronRequests'
      preLoaderRoute: typeof _authenticatedIllPatronRequestsRouteImport
      parentRoute: typeof _authenticatedIllRoute
    }
    '/__authenticated/ill/login': {
      id: '/__authenticated/ill/login'
      path: '/login'
      fullPath: '/ill/login'
      preLoaderRoute: typeof _authenticatedIllLoginRouteImport
      parentRoute: typeof _authenticatedIllRoute
    }
    '/__authenticated/requesting/$recordId/': {
      id: '/__authenticated/requesting/$recordId/'
      path: '/requesting/$recordId'
      fullPath: '/requesting/$recordId'
      preLoaderRoute: typeof _authenticatedRequestingRecordIdIndexRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/patronRequests/$id/': {
      id: '/__authenticated/patronRequests/$id/'
      path: '/patronRequests/$id'
      fullPath: '/patronRequests/$id'
      preLoaderRoute: typeof _authenticatedPatronRequestsIdIndexRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/locations/$id/': {
      id: '/__authenticated/locations/$id/'
      path: '/locations/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof _authenticatedLocationsIdIndexRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/indexes/$indexCode/': {
      id: '/__authenticated/indexes/$indexCode/'
      path: '/indexes/$indexCode'
      fullPath: '/indexes/$indexCode'
      preLoaderRoute: typeof _authenticatedIndexesIndexCodeIndexRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/patronRequests/audits/$auditId/': {
      id: '/__authenticated/patronRequests/audits/$auditId/'
      path: '/patronRequests/audits/$auditId'
      fullPath: '/patronRequests/audits/$auditId'
      preLoaderRoute: typeof _authenticatedPatronRequestsAuditsAuditIdIndexRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/indexes/$indexCode/$recordId/': {
      id: '/__authenticated/indexes/$indexCode/$recordId/'
      path: '/indexes/$indexCode/$recordId'
      fullPath: '/indexes/$indexCode/$recordId'
      preLoaderRoute: typeof _authenticatedIndexesIndexCodeRecordIdIndexRouteImport
      parentRoute: typeof _authenticatedRoute
    }
  }
}

interface _authenticatedIllRouteChildren {
  _authenticatedIllLoginRoute: typeof _authenticatedIllLoginRoute
  _authenticatedIllPatronRequestsRoute: typeof _authenticatedIllPatronRequestsRoute
}

const _authenticatedIllRouteChildren: _authenticatedIllRouteChildren = {
  _authenticatedIllLoginRoute: _authenticatedIllLoginRoute,
  _authenticatedIllPatronRequestsRoute: _authenticatedIllPatronRequestsRoute,
}

const _authenticatedIllRouteWithChildren =
  _authenticatedIllRoute._addFileChildren(_authenticatedIllRouteChildren)

interface _authenticatedRouteChildren {
  _authenticatedContactsRoute: typeof _authenticatedContactsRoute
  _authenticatedDataChangeLogRoute: typeof _authenticatedDataChangeLogRoute
  _authenticatedIllRoute: typeof _authenticatedIllRouteWithChildren
  _authenticatedMappingsRoute: typeof _authenticatedMappingsRoute
  _authenticatedServiceRoute: typeof _authenticatedServiceRoute
  _authenticatedSettingsRoute: typeof _authenticatedSettingsRoute
  _authenticatedSupplierRequestsRoute: typeof _authenticatedSupplierRequestsRoute
  _authenticatedIndexRoute: typeof _authenticatedIndexRoute
  _authenticatedLocationsIndexRoute: typeof _authenticatedLocationsIndexRoute
  _authenticatedPatronRequestsIndexRoute: typeof _authenticatedPatronRequestsIndexRoute
  _authenticatedRequestingIndexRoute: typeof _authenticatedRequestingIndexRoute
  _authenticatedIndexesIndexCodeIndexRoute: typeof _authenticatedIndexesIndexCodeIndexRoute
  _authenticatedLocationsIdIndexRoute: typeof _authenticatedLocationsIdIndexRoute
  _authenticatedPatronRequestsIdIndexRoute: typeof _authenticatedPatronRequestsIdIndexRoute
  _authenticatedRequestingRecordIdIndexRoute: typeof _authenticatedRequestingRecordIdIndexRoute
  _authenticatedIndexesIndexCodeRecordIdIndexRoute: typeof _authenticatedIndexesIndexCodeRecordIdIndexRoute
  _authenticatedPatronRequestsAuditsAuditIdIndexRoute: typeof _authenticatedPatronRequestsAuditsAuditIdIndexRoute
}

const _authenticatedRouteChildren: _authenticatedRouteChildren = {
  _authenticatedContactsRoute: _authenticatedContactsRoute,
  _authenticatedDataChangeLogRoute: _authenticatedDataChangeLogRoute,
  _authenticatedIllRoute: _authenticatedIllRouteWithChildren,
  _authenticatedMappingsRoute: _authenticatedMappingsRoute,
  _authenticatedServiceRoute: _authenticatedServiceRoute,
  _authenticatedSettingsRoute: _authenticatedSettingsRoute,
  _authenticatedSupplierRequestsRoute: _authenticatedSupplierRequestsRoute,
  _authenticatedIndexRoute: _authenticatedIndexRoute,
  _authenticatedLocationsIndexRoute: _authenticatedLocationsIndexRoute,
  _authenticatedPatronRequestsIndexRoute:
    _authenticatedPatronRequestsIndexRoute,
  _authenticatedRequestingIndexRoute: _authenticatedRequestingIndexRoute,
  _authenticatedIndexesIndexCodeIndexRoute:
    _authenticatedIndexesIndexCodeIndexRoute,
  _authenticatedLocationsIdIndexRoute: _authenticatedLocationsIdIndexRoute,
  _authenticatedPatronRequestsIdIndexRoute:
    _authenticatedPatronRequestsIdIndexRoute,
  _authenticatedRequestingRecordIdIndexRoute:
    _authenticatedRequestingRecordIdIndexRoute,
  _authenticatedIndexesIndexCodeRecordIdIndexRoute:
    _authenticatedIndexesIndexCodeRecordIdIndexRoute,
  _authenticatedPatronRequestsAuditsAuditIdIndexRoute:
    _authenticatedPatronRequestsAuditsAuditIdIndexRoute,
}

const _authenticatedRouteWithChildren = _authenticatedRoute._addFileChildren(
  _authenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _authenticatedRoute: _authenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
