/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SupplierRequestsImport } from './routes/supplierRequests'
import { Route as SettingsImport } from './routes/settings'
import { Route as ServiceImport } from './routes/service'
import { Route as MappingsImport } from './routes/mappings'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as LocationsImport } from './routes/locations'
import { Route as DataChangeLogImport } from './routes/dataChangeLog'
import { Route as ContactsImport } from './routes/contacts'
import { Route as IndexImport } from './routes/index'
import { Route as SharedIndexIndexImport } from './routes/sharedIndex/index'
import { Route as PatronRequestsIndexImport } from './routes/patronRequests/index'
import { Route as LocationsIndexImport } from './routes/locations/index'
import { Route as SharedIndexIdIndexImport } from './routes/sharedIndex/$id/index'
import { Route as PatronRequestsIdIndexImport } from './routes/patronRequests/$id/index'
import { Route as LocationsIdIndexImport } from './routes/locations/$id/index'
import { Route as SharedIndexIdItemsImport } from './routes/sharedIndex/$id/items'
import { Route as SharedIndexIdIdentifiersImport } from './routes/sharedIndex/$id/identifiers'
import { Route as SharedIndexIdClusterImport } from './routes/sharedIndex/$id/cluster'

// Create/Update Routes

const SupplierRequestsRoute = SupplierRequestsImport.update({
  id: '/supplierRequests',
  path: '/supplierRequests',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ServiceRoute = ServiceImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRoute,
} as any)

const MappingsRoute = MappingsImport.update({
  id: '/mappings',
  path: '/mappings',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LocationsRoute = LocationsImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRoute,
} as any)

const DataChangeLogRoute = DataChangeLogImport.update({
  id: '/dataChangeLog',
  path: '/dataChangeLog',
  getParentRoute: () => rootRoute,
} as any)

const ContactsRoute = ContactsImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SharedIndexIndexRoute = SharedIndexIndexImport.update({
  id: '/sharedIndex/',
  path: '/sharedIndex/',
  getParentRoute: () => rootRoute,
} as any)

const PatronRequestsIndexRoute = PatronRequestsIndexImport.update({
  id: '/patronRequests/',
  path: '/patronRequests/',
  getParentRoute: () => rootRoute,
} as any)

const LocationsIndexRoute = LocationsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocationsRoute,
} as any)

const SharedIndexIdIndexRoute = SharedIndexIdIndexImport.update({
  id: '/sharedIndex/$id/',
  path: '/sharedIndex/$id/',
  getParentRoute: () => rootRoute,
} as any)

const PatronRequestsIdIndexRoute = PatronRequestsIdIndexImport.update({
  id: '/patronRequests/$id/',
  path: '/patronRequests/$id/',
  getParentRoute: () => rootRoute,
} as any)

const LocationsIdIndexRoute = LocationsIdIndexImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => LocationsRoute,
} as any)

const SharedIndexIdItemsRoute = SharedIndexIdItemsImport.update({
  id: '/sharedIndex/$id/items',
  path: '/sharedIndex/$id/items',
  getParentRoute: () => rootRoute,
} as any)

const SharedIndexIdIdentifiersRoute = SharedIndexIdIdentifiersImport.update({
  id: '/sharedIndex/$id/identifiers',
  path: '/sharedIndex/$id/identifiers',
  getParentRoute: () => rootRoute,
} as any)

const SharedIndexIdClusterRoute = SharedIndexIdClusterImport.update({
  id: '/sharedIndex/$id/cluster',
  path: '/sharedIndex/$id/cluster',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsImport
      parentRoute: typeof rootRoute
    }
    '/dataChangeLog': {
      id: '/dataChangeLog'
      path: '/dataChangeLog'
      fullPath: '/dataChangeLog'
      preLoaderRoute: typeof DataChangeLogImport
      parentRoute: typeof rootRoute
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/mappings': {
      id: '/mappings'
      path: '/mappings'
      fullPath: '/mappings'
      preLoaderRoute: typeof MappingsImport
      parentRoute: typeof rootRoute
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/supplierRequests': {
      id: '/supplierRequests'
      path: '/supplierRequests'
      fullPath: '/supplierRequests'
      preLoaderRoute: typeof SupplierRequestsImport
      parentRoute: typeof rootRoute
    }
    '/locations/': {
      id: '/locations/'
      path: '/'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexImport
      parentRoute: typeof LocationsImport
    }
    '/patronRequests/': {
      id: '/patronRequests/'
      path: '/patronRequests'
      fullPath: '/patronRequests'
      preLoaderRoute: typeof PatronRequestsIndexImport
      parentRoute: typeof rootRoute
    }
    '/sharedIndex/': {
      id: '/sharedIndex/'
      path: '/sharedIndex'
      fullPath: '/sharedIndex'
      preLoaderRoute: typeof SharedIndexIndexImport
      parentRoute: typeof rootRoute
    }
    '/sharedIndex/$id/cluster': {
      id: '/sharedIndex/$id/cluster'
      path: '/sharedIndex/$id/cluster'
      fullPath: '/sharedIndex/$id/cluster'
      preLoaderRoute: typeof SharedIndexIdClusterImport
      parentRoute: typeof rootRoute
    }
    '/sharedIndex/$id/identifiers': {
      id: '/sharedIndex/$id/identifiers'
      path: '/sharedIndex/$id/identifiers'
      fullPath: '/sharedIndex/$id/identifiers'
      preLoaderRoute: typeof SharedIndexIdIdentifiersImport
      parentRoute: typeof rootRoute
    }
    '/sharedIndex/$id/items': {
      id: '/sharedIndex/$id/items'
      path: '/sharedIndex/$id/items'
      fullPath: '/sharedIndex/$id/items'
      preLoaderRoute: typeof SharedIndexIdItemsImport
      parentRoute: typeof rootRoute
    }
    '/locations/$id/': {
      id: '/locations/$id/'
      path: '/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof LocationsIdIndexImport
      parentRoute: typeof LocationsImport
    }
    '/patronRequests/$id/': {
      id: '/patronRequests/$id/'
      path: '/patronRequests/$id'
      fullPath: '/patronRequests/$id'
      preLoaderRoute: typeof PatronRequestsIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/sharedIndex/$id/': {
      id: '/sharedIndex/$id/'
      path: '/sharedIndex/$id'
      fullPath: '/sharedIndex/$id'
      preLoaderRoute: typeof SharedIndexIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface LocationsRouteChildren {
  LocationsIndexRoute: typeof LocationsIndexRoute
  LocationsIdIndexRoute: typeof LocationsIdIndexRoute
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsIndexRoute: LocationsIndexRoute,
  LocationsIdIndexRoute: LocationsIdIndexRoute,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/dataChangeLog': typeof DataChangeLogRoute
  '/locations': typeof LocationsRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/mappings': typeof MappingsRoute
  '/service': typeof ServiceRoute
  '/settings': typeof SettingsRoute
  '/supplierRequests': typeof SupplierRequestsRoute
  '/locations/': typeof LocationsIndexRoute
  '/patronRequests': typeof PatronRequestsIndexRoute
  '/sharedIndex': typeof SharedIndexIndexRoute
  '/sharedIndex/$id/cluster': typeof SharedIndexIdClusterRoute
  '/sharedIndex/$id/identifiers': typeof SharedIndexIdIdentifiersRoute
  '/sharedIndex/$id/items': typeof SharedIndexIdItemsRoute
  '/locations/$id': typeof LocationsIdIndexRoute
  '/patronRequests/$id': typeof PatronRequestsIdIndexRoute
  '/sharedIndex/$id': typeof SharedIndexIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/dataChangeLog': typeof DataChangeLogRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/mappings': typeof MappingsRoute
  '/service': typeof ServiceRoute
  '/settings': typeof SettingsRoute
  '/supplierRequests': typeof SupplierRequestsRoute
  '/locations': typeof LocationsIndexRoute
  '/patronRequests': typeof PatronRequestsIndexRoute
  '/sharedIndex': typeof SharedIndexIndexRoute
  '/sharedIndex/$id/cluster': typeof SharedIndexIdClusterRoute
  '/sharedIndex/$id/identifiers': typeof SharedIndexIdIdentifiersRoute
  '/sharedIndex/$id/items': typeof SharedIndexIdItemsRoute
  '/locations/$id': typeof LocationsIdIndexRoute
  '/patronRequests/$id': typeof PatronRequestsIdIndexRoute
  '/sharedIndex/$id': typeof SharedIndexIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/dataChangeLog': typeof DataChangeLogRoute
  '/locations': typeof LocationsRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/mappings': typeof MappingsRoute
  '/service': typeof ServiceRoute
  '/settings': typeof SettingsRoute
  '/supplierRequests': typeof SupplierRequestsRoute
  '/locations/': typeof LocationsIndexRoute
  '/patronRequests/': typeof PatronRequestsIndexRoute
  '/sharedIndex/': typeof SharedIndexIndexRoute
  '/sharedIndex/$id/cluster': typeof SharedIndexIdClusterRoute
  '/sharedIndex/$id/identifiers': typeof SharedIndexIdIdentifiersRoute
  '/sharedIndex/$id/items': typeof SharedIndexIdItemsRoute
  '/locations/$id/': typeof LocationsIdIndexRoute
  '/patronRequests/$id/': typeof PatronRequestsIdIndexRoute
  '/sharedIndex/$id/': typeof SharedIndexIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/dataChangeLog'
    | '/locations'
    | '/login'
    | '/logout'
    | '/mappings'
    | '/service'
    | '/settings'
    | '/supplierRequests'
    | '/locations/'
    | '/patronRequests'
    | '/sharedIndex'
    | '/sharedIndex/$id/cluster'
    | '/sharedIndex/$id/identifiers'
    | '/sharedIndex/$id/items'
    | '/locations/$id'
    | '/patronRequests/$id'
    | '/sharedIndex/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/dataChangeLog'
    | '/login'
    | '/logout'
    | '/mappings'
    | '/service'
    | '/settings'
    | '/supplierRequests'
    | '/locations'
    | '/patronRequests'
    | '/sharedIndex'
    | '/sharedIndex/$id/cluster'
    | '/sharedIndex/$id/identifiers'
    | '/sharedIndex/$id/items'
    | '/locations/$id'
    | '/patronRequests/$id'
    | '/sharedIndex/$id'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/dataChangeLog'
    | '/locations'
    | '/login'
    | '/logout'
    | '/mappings'
    | '/service'
    | '/settings'
    | '/supplierRequests'
    | '/locations/'
    | '/patronRequests/'
    | '/sharedIndex/'
    | '/sharedIndex/$id/cluster'
    | '/sharedIndex/$id/identifiers'
    | '/sharedIndex/$id/items'
    | '/locations/$id/'
    | '/patronRequests/$id/'
    | '/sharedIndex/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRoute
  DataChangeLogRoute: typeof DataChangeLogRoute
  LocationsRoute: typeof LocationsRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  MappingsRoute: typeof MappingsRoute
  ServiceRoute: typeof ServiceRoute
  SettingsRoute: typeof SettingsRoute
  SupplierRequestsRoute: typeof SupplierRequestsRoute
  PatronRequestsIndexRoute: typeof PatronRequestsIndexRoute
  SharedIndexIndexRoute: typeof SharedIndexIndexRoute
  SharedIndexIdClusterRoute: typeof SharedIndexIdClusterRoute
  SharedIndexIdIdentifiersRoute: typeof SharedIndexIdIdentifiersRoute
  SharedIndexIdItemsRoute: typeof SharedIndexIdItemsRoute
  PatronRequestsIdIndexRoute: typeof PatronRequestsIdIndexRoute
  SharedIndexIdIndexRoute: typeof SharedIndexIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRoute,
  DataChangeLogRoute: DataChangeLogRoute,
  LocationsRoute: LocationsRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  MappingsRoute: MappingsRoute,
  ServiceRoute: ServiceRoute,
  SettingsRoute: SettingsRoute,
  SupplierRequestsRoute: SupplierRequestsRoute,
  PatronRequestsIndexRoute: PatronRequestsIndexRoute,
  SharedIndexIndexRoute: SharedIndexIndexRoute,
  SharedIndexIdClusterRoute: SharedIndexIdClusterRoute,
  SharedIndexIdIdentifiersRoute: SharedIndexIdIdentifiersRoute,
  SharedIndexIdItemsRoute: SharedIndexIdItemsRoute,
  PatronRequestsIdIndexRoute: PatronRequestsIdIndexRoute,
  SharedIndexIdIndexRoute: SharedIndexIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contacts",
        "/dataChangeLog",
        "/locations",
        "/login",
        "/logout",
        "/mappings",
        "/service",
        "/settings",
        "/supplierRequests",
        "/patronRequests/",
        "/sharedIndex/",
        "/sharedIndex/$id/cluster",
        "/sharedIndex/$id/identifiers",
        "/sharedIndex/$id/items",
        "/patronRequests/$id/",
        "/sharedIndex/$id/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/contacts": {
      "filePath": "contacts.tsx"
    },
    "/dataChangeLog": {
      "filePath": "dataChangeLog.tsx"
    },
    "/locations": {
      "filePath": "locations.tsx",
      "children": [
        "/locations/",
        "/locations/$id/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/mappings": {
      "filePath": "mappings.tsx"
    },
    "/service": {
      "filePath": "service.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/supplierRequests": {
      "filePath": "supplierRequests.tsx"
    },
    "/locations/": {
      "filePath": "locations/index.tsx",
      "parent": "/locations"
    },
    "/patronRequests/": {
      "filePath": "patronRequests/index.tsx"
    },
    "/sharedIndex/": {
      "filePath": "sharedIndex/index.tsx"
    },
    "/sharedIndex/$id/cluster": {
      "filePath": "sharedIndex/$id/cluster.tsx"
    },
    "/sharedIndex/$id/identifiers": {
      "filePath": "sharedIndex/$id/identifiers.tsx"
    },
    "/sharedIndex/$id/items": {
      "filePath": "sharedIndex/$id/items.tsx"
    },
    "/locations/$id/": {
      "filePath": "locations/$id/index.tsx",
      "parent": "/locations"
    },
    "/patronRequests/$id/": {
      "filePath": "patronRequests/$id/index.tsx"
    },
    "/sharedIndex/$id/": {
      "filePath": "sharedIndex/$id/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
